version: "3"
services:

  wiki:
    image: requarks/wiki:2
    restart: unless-stopped
    environment:
      DB_TYPE: postgres
      DB_HOST: postgresql-primary
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: $DB_PASS
      DB_NAME: wikijs
    volumes:
      - /etc/wikijs:/etc/wikijs
    networks:
      - proxy
      - postgresql-primary-backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kb-secure.entrypoints=https"
      - "traefik.http.routers.kb-secure.rule=Host(`kb.argonaut.network`)"
      - "traefik.http.routers.kb-secure.tls=true"
      - "traefik.docker.network=proxy"
      
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  proxy:
    external: true
  postgresql-primary-backend:
    external: true
